export { createEncounterService } from "./encounter.service"
export { systemClock } from "../utils/clock"
export type { Clock } from "../utils/clock"
export { createMemoryEncounterRepository } from "./encounter.repository"
export { assertTransition, canTransition } from "./encounter.state"
export type { EncounterPort, EncounterRecord, EncounterStatus } from "./encounter.types"
export type { EncounterRepository } from "./encounter.repository"
export type { EncounterServiceDeps } from "./encounter.service"
