export const APP_ERROR_CODES = [
  "MODEL_NOT_READY",
  "MIC_PERMISSION_DENIED",
  "AUDIO_CAPTURE_FAILED",
  "TRANSCRIPTION_FAILED",
  "INVALID_STRUCTURED_OUTPUT",
  "DATABASE_ERROR",
  "EXPORT_FAILED",
  "LOW_MEMORY",
  "DISK_FULL",
  "INVALID_INPUT",
  "PATH_TRAVERSAL_BLOCKED",
  "NOT_AUTHENTICATED",
  "INVALID_STATE_TRANSITION",
  "ENCOUNTER_ACTIVE",
  "OPERATION_CANCELLED",
  "AUDIO_FORMAT_UNSUPPORTED",
  "MODEL_DOWNLOAD_FAILED",
] as const

export type AppErrorCode = (typeof APP_ERROR_CODES)[number]
